site_name: CommonRoad To Autoware Interface

theme:
  name: readthedocs
  logo: assets/commonroad_white150.png

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: false
            heading_level: 3
            show_module_names: False
  - search

nav:
  - Introduction:
    - "Introduction": index.md

  - Architecture:
      - "Architecture": architecture.md
      - "Core Algorithms": core_algorithm.md
      - "Conversions": conversions.md

  - Main Node:
      - "CommonRoad to Autoware Node": cr2aw_node.md

  - Handlers:
      - "Base Handler": base_handler.md
      - "Data Generation Handler": data_generation_handler.md
      - "ROS2 Humble API Handler": api_handler.md
      - "Ego Vehicle Handler": ego_vehicle_handler.md
      - "Planning Problem Handler": planning_problem_handler.md
      - "Scenario Handler": scenario_handler.md
      - "Spot Handler": spot_handler.md

  - Configuration:
      - "Configuration": configuration.md

  - ROS2 Interface Specs:
      - "Creation": spec_create.md
      - "Base Spec": spec_base.md
      - "Client Spec": spec_client.md
      - "Publisher Spec": spec_publisher.md
      - "Subscription Spec": spec_subscriber.md



  - CommonRoad Planning Interfaces:
      - Abstract Base Interfaces:
        - "Base Route Planner Interface": base_route_interface.md
        - "Base Trajectory Planner Interface": base_trajectory_interface.md

      - CommonRoad Interfaces:
          - "CommonRoad Route Planner Interface": cr_route_planner_interface.md
          - "CommonRoad Reactive Planner Interface": cr_reactive_planner_interface.md
          - "CommonRoad Velocity Planner Interface": cr_velocity_planner_interface.md


  - Data Generation:
      - "Work in Progress": placeholder.md
  #    - "Rosbag Saver": index.md
  #    - "MCAP to CommonRoad Converter": index.md


  - Utils:
      - "Utils":
        - "CR2AW Conversion Utils": utils_conversion.md
        - "Debug Utils": utils_debug.md
        - "Geometry Utils": utils_geometry.md
        - "General Utils": utils_general.md
        - "Message Utils": utils_message.md
        - "TF2 geometry_msgs Utils": utils_tf2_geometry_msgs.md
        - "TrajectoryLogger Utils": utils_trajectory_logger.md
        - "Transform Utils": utils_transform.md
        - "Type Mapping Utils": utils_type_mapping.md
        - "Visualization Utils": utils_visualization.md







