/**:
  ros__parameters:
    general:
      map_path: ""
      solution_file: ""
      enable_spot: False # enable spot
      detailed_log: True
      write_scenario: True # write generated scenario as xml file after map is converted
      plot_scenario: False
      store_trajectory: False
      store_trajectory_file: "output/solutions/solution1.xml" # CommonRoad solution file path

    scenario:
      dt: 0.1
      left_driving: True
      adjacencies: False
      publish_obstacles: True # publish static and dynamic obstacles from CommonRoad scenario

    vehicle:
      cg_to_front: 1.0 # meter
      cg_to_rear: 1.0 # meter
      width: 2.0 # meter
      front_overhang: 0.5 # meter
      rear_overhang: 0.5 # meter
      max_velocity: 10.0 # m/s
      min_velocity: 0.0 # m/s

    velocity_planner:
      init_velocity: 5.0 # m/s - not yet implemented; should only be used for lanelet2 maps
      lookahead_dist: 3.0 # m
      lookahead_time: 0.8 # s

    trajectory_planner:
      trajectory_planner_type: 1 # 1: reactive planner
      planner_update_time: 0.5 # run each x.x seconds
      planning_horizon: 5.0

    rp_interface:
      default_yaml_folder: "../../../../src/universe/autoware.universe/planning/tum_commonroad_planning/reactive-planner/configurations/defaults/"
      d_min: -3
      d_max: 3
      # minimum time sampling in s (t_max is given by planning horizon)
      t_min: 0.4
