/**:
  ros__parameters:
    general:
      map_path: ""
      solution_file: ""
      enable_spot: False # enable spot
      detailed_log: True
      write_scenario: True # write generated scenario as xml file after map is converted
      plot_scenario: False
      store_trajectory: False
      store_trajectory_file: "output/solutions/solution1.xml" # CommonRoad solution file path

    scenario:
      dt: 0.1
      left_driving: True
      adjacencies: False
      publish_obstacles: True # publish static and dynamic obstacles from CommonRoad scenario

    vehicle:
      # relevant parameters from vehicle_info.param.yaml (TODO: get directly from vehicle description package)
      # TODO: EDGAR values (make configurable)
#      wheel_base: 3.128 # meter
#      wheel_tread: 1.645 # meter
#      front_overhang: 0.952 # meter
#      rear_overhang: 0.897 # meter
#      left_overhang: 0.304 # meter
#      right_overhang: 0.304 # meter
#      max_steer_angle: 0.610865  # rad
#      # kinamatic single track params
#      wb_front_axle: 1.484 # meter
#      wb_rear_axle: 1.644 # meter

      # TODO: Sample vehicle values (make configurable)
      wheel_base: 2.79 # meter
      wheel_tread: 1.64 # meter
      front_overhang: 1.0 # meter
      rear_overhang: 1.1 # meter
      left_overhang: 0.128 # meter
      right_overhang: 0.128 # meter
      max_steer_angle: 0.70  # rad
      # kinamatic single track params
      wb_front_axle: 1.395 # meter
      wb_rear_axle: 1.395 # meter

      # other params
      max_velocity: 10.0 # m/s (TODO: not used?)
      min_velocity: 0.0 # m/s (TODO: not used?)
      max_acceleration: 10.0  # m/s^2 (lon. acceleration limit for planning)

    velocity_planner:
      init_velocity: 5.0 # m/s - not yet implemented; should only be used for lanelet2 maps
      lookahead_dist: 3.0 # m
      lookahead_time: 0.8 # s

    trajectory_planner:
      trajectory_planner_type: 1 # 1: reactive planner
      planner_update_time: 0.5 # run each x.x seconds
      planning_horizon: 5.0

    rp_interface:
      default_yaml_folder: "../../../../src/universe/autoware.universe/planning/tum_commonroad_planning/reactive-planner/configurations/defaults/"
      d_min: -3.0
      d_max: 3.0
      # minimum time sampling in s (t_max is given by planning horizon)
      t_min: 0.4
