---

/**:
  ros__parameters:
    map_osm_file: "/root/workspace/dfg-car/src/cr2autoware/data/sample-map-planning/lanelet2_map.osm"
    latitude: 35.238094905136874
    longitude: 139.90095439549778
    elevation: 1.0
    origin_offset_lat: -5.239983224214484e-06
    origin_offset_lon: 4.5845488187978845e-06
    left_driving: True
    adjacencies: False 

    vehicle:
      cg_to_front_m: 1.0
      cg_to_rear_m: 1.0
      width_m: 2.0
      front_overhang_m: 0.5
      rear_overhang_m: 0.5