---

/**:
  ros__parameters:
    map_osm_file: "/root/workspace/dfg-car/src/cr2autoware/data/sample-map-planning/lanelet2_map.osm"
    latitude: 35.238094905136874
    longitude: 139.90095439549778
    proj_str: "+proj=utm +zone=54 +datum=WGS84 +ellps=WGS84"
    elevation: 1.0
    origin_offset_lat: -5.239983224214484e-06
    origin_offset_lon: 4.5845488187978845e-06
    left_driving: True
    adjacencies: False
    write_scenario: False # write generated scenario as xml file after map is converted
    plot_scenario: False
    map_filename: "/root/workspace/dfg-car/src/cr2autoware/data/Autoware_Map-1_1.xml" # name of the offline-scenario
    scenario_update_time: 0.25 # run each x.x seconds
    planner_update_time: 0.5 # run each x.x seconds
    goal_is_reached_update_time: 0.1 # run each x.x seconds

    vehicle:
      cg_to_front: 1.0 # meter
      cg_to_rear: 1.0 # meter
      width: 2.0 # meter
      front_overhang: 0.5 # meter
      rear_overhang: 0.5 # meter
      max_velocity: 10.0 # m/s
      min_velocity: 0.0 # m/s

      # Planner type #1: Search based planner (default), #2: reactive planner
    planner_type: 2

    # parameters for reactive planner
    reactive_planner:
      default_yaml_folder: "/root/workspace/reactive-planner/configurations/defaults/"
      sampling:
        # lateral sampling interval
        d_min: -3
        d_max: 3
        # minimum time sampling in s (t_max is given by planning horizon)
        t_min: 0.1

      planning:
        # planner time step (in s)
        dt: 0.1
        # planning time horizon (in s)
        planning_horizon: 5.0