---

/**:
  ros__parameters:
    map_osm_path: "sample-map-planning"
    proj_str: "+proj=utm +zone=54 +datum=WGS84 +ellps=WGS84"
    left_driving: True
    adjacencies: False
    write_scenario: True # write generated scenario as xml file after map is converted
    plot_scenario: False
    filename: "cr2autoware_output.xml" # name of the scenario for saving
    scenario_update_time: 0.25 # run each x.x seconds
    planner_update_time: 0.5 # run each x.x seconds
    goal_is_reached_update_time: 0.1 # run each x.x seconds
    detailed_log: True

    vehicle:
      cg_to_front: 1.0 # meter
      cg_to_rear: 1.0 # meter
      width: 2.0 # meter
      front_overhang: 0.5 # meter
      rear_overhang: 0.5 # meter
      max_velocity: 10.0 # m/s
      min_velocity: 0.0 # m/s

      # Planner type #1: Search based planner (default), #2: reactive planner
    planner_type: 2

    # parameters for reactive planner
    reactive_planner:
      default_yaml_folder: "src/universe/autoware.universe/planning/tum_commonroad_planning/cr2autoware/param/"
      sampling:
        # lateral sampling interval
        d_min: -3
        d_max: 3
        # minimum time sampling in s (t_max is given by planning horizon)
        t_min: 0.1

      planning:
        # planner time step (in s)
        dt: 0.1
        # planning time horizon (in s)
        planning_horizon: 5.0
